version: "3.7"
services:
  #Node Service
  apiserver:
    build: .
    container_name: apiserver
    restart: always
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    ports:
      - "3333:8080"
    networks:
      - app-network

  #Postgres Service
  db:
    build: docker/postgres
    container_name: "db"
    restart: always
    ports:
      - "32768:5432"
    environment:
      - POSTGRES_MULTIPLE_DATABASES=erp,erp_testing
      - POSTGRES_USER=docker_erp_user
      - POSTGRES_PASSWORD=docker_erp_password
    volumes:
      - my_dbdata:/var/lib/postgresql/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  my_dbdata:
    driver: local
